services:
    app:
        image: app:latest
        container_name: rental_backend
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            POSTGRES_HOST: host.docker.internal
            POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
            POSTGRES_PORT: "${POSTGRES_PORT}"
            PORT: "${BACKEND_PORT}"
            SCHEDULED_SCRAPER: "${SCHEDULED_SCRAPER}"
            SCHEDULED_DATABASE: "${SCHEDULED_DATABASE}"
        env_file:
            - .env
        networks:
            - rental-network
    frontend:
        image: frontend:latest
        container_name: rental_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3030:3030"
        depends_on:
            - app
        environment:
            REACT_APP_API_URL: "${REACT_APP_API_URL}"
            PORT: "${FRONTEND_PORT}"
        env_file:
            - .env
        networks:
            - rental-network
networks:
    rental-network:
        driver: bridge
