services:
    app:
        image: app:latest
        container_name: rental_backend
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8800:8800"
        environment:
            DATABASE_URL: "${DATABASE_URL}"
            PORT: "${BACKEND_PORT}"
            SCHEDULED_SCRAPER: "${SCHEDULED_SCRAPER}"
            SCHEDULED_DATABASE: "${SCHEDULED_DATABASE}"
        env_file:
            - .env.render
        networks:
            - rental-network
    frontend:
        image: frontend:latest
        container_name: rental_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - app
        environment:
            REACT_APP_API_URL: "${REACT_APP_API_URL}"
            PORT: "${FRONTEND_PORT}"
        env_file:
            - .env.render
        networks:
            - rental-network
networks:
    rental-network:
        driver: bridge
