services:
    rentaldb:
      image: postgres
      hostname: localhost
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
      ports:
          - "5433:5432"    
      volumes:
          - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 5s
            timeout: 60s
            retries: 5
            start_period: 80s
    frontend:
        image: frontend:latest
        container_name: rental_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - app
    app:
        image: app:latest
        container_name: rental_backend
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8800:8800"
        environment:
          POSTGRES_USER: "${POSTGRES_USER}"
          POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
          POSTGRES_DB: "${POSTGRES_DB}"        
        depends_on:
            - postgres

